import {COUPLE_PROFILE,partnerOf} from "../data/couple-profile.js";import {MESSAGES,pick} from "../data/messages.js";import {escapeHtml,formatDate} from "./utils.js";import {isConfigured,state} from "./state.js";
const app=()=>document.querySelector("#app");export const toast=(text)=>{const e=document.querySelector("#toast");e.textContent=text;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)};
const button=(text,action,cls="button")=>`<button class="${cls}" data-action="${action}">${text}</button>`;
export function renderIdentity(){app().innerHTML=`<section class="card hero"><h1>嗨，先選一下你是誰</h1><p>這只會儲存在這支裝置，之後可以到設定切換。</p>${button("我是大爺","identity:ken")}${button("我是阡阡","identity:chien","button secondary")}</section>`}
export function renderHome(){const u=COUPLE_PROFILE.users[state.userId],profile=COUPLE_PROFILE;app().innerHTML=`<section class="card hero"><span class="badge">${isConfigured()?"共同資料庫已連線":"Mock 模式"}</span><h1>${profile.welcome[state.userId]}</h1><p>${pick(MESSAGES.greetings)}</p></section><section class="menu-grid"><button class="menu-card" data-route="dinner">🍽️<strong>今晚吃什麼</strong><small>快速抽或秘密配對</small></button><button class="menu-card" data-route="activity">🏠<strong>今天做什麼</strong><small>80 種活動靈感</small></button><button class="menu-card" data-route="games">🎮<strong>雙人遊戲室</strong><small>默契來一下</small></button><button class="menu-card" data-route="pending">◷<strong>等待對方回答</strong><small>看看邀請進度</small></button></section><section class="card"><h2>你們的共同小宇宙</h2><div class="stat"><span>目前共同積分</span><b>${state.history.reduce((n,x)=>n+(x.points||0),0)} 分</b></div><div class="stat"><span>最近共同結果</span><span>${state.history[0]?.title||"還沒有，快來玩一局"}</span></div><div class="stat"><span>${COUPLE_PROFILE.users[partnerOf(state.userId)].displayName} 狀態</span><span>等下一個邀請</span></div></section><p class="version">目前使用者：${u.displayName}</p>`}
export function renderDinner(){app().innerHTML=`<h1>今晚吃什麼</h1><section class="card"><h2>單人快速決定</h2><p>現在很餓？交給系統抽三個可行選項。</p>${button("幫我推薦","quick-dinner")}</section><section class="card"><h2>雙人秘密配對</h2><p>各自選好才會公布，不能偷看。</p>${button("建立晚餐邀請","new-room:dinner")}</section>`}
export function dinnerForm(room){app().innerHTML=`<h1>${room?"秘密晚餐配對":"晚餐偏好"}</h1>${room?`<section class="card"><p>先把邀請傳給對方，答案會保密到雙方完成。</p>${button("分享 LINE 邀請","share-room","button secondary")}</section>`:""}<form id="dinner-form" class="card"><div class="form-group"><label>今天的狀態</label><select name="mood">${["認真減脂","正常控制","今天可以稍微放縱","工作很累，需要吃好一點","沒什麼胃口","肚子快餓扁","不想思考，交給系統"].map(x=>`<option>${x}</option>`).join("")}</select></div><div class="form-group"><label>預算</label><select name="budget"><option value="200">每人 200 元內</option><option value="400">每人 400 元內</option><option value="600">每人 600 元內</option><option value="1000">每人 1,000 元內</option><option value="9999">今天不限制</option></select></div><div class="form-group"><label>食物類型（可複選）</label><div class="chip-row">${["火鍋","燒肉","麵類","飯類","海鮮","日式","韓式","泰式","越式","健康餐","小吃","超商","自己煮","甜點或飲料"].map(x=>`<button type="button" class="chip" data-chip="${x}">${x}</button>`).join("")}</div></div><div class="form-group"><label>其他條件（可複選）</label><div class="chip-row">${["想吃熱的","想吃清淡","想吃肉","想吃蔬菜","不想排隊","可以騎車或開車","只想吃附近","家裡有剩菜","晚餐後還要運動","今天不想洗碗"].map(x=>`<button type="button" class="chip" data-condition="${x}">${x}</button>`).join("")}</div></div>${button("送出選擇","submit-dinner")}</form>`}
export function renderResult(result,title="共同結果"){app().innerHTML=`<h1>${title}</h1><section class="card reveal"><div class="result-score">${result.score||"?"}%</div><h2 style="text-align:center">${result.score>=80?"哇噻哇噻！你們今天很有默契！":"昏倒，但還是找得到折衷方案。"}</h2>${result.compromise?`<p class="notice">${result.compromise}</p>`:""}${(result.items||[]).map((x,i)=>`<article class="card recommendation"><h3>${i+1}. ${escapeHtml(x.title)}</h3><p>配對 ${x.score}%｜${x.foodType?.join("、")||""}</p><small>符合預算與今天的節奏；點餐時記得互相保留一次否決權。</small></article>`).join("")}${button("命運轉盤","wheel","button secondary")}${button("回首頁","route:home","button ghost")}</section>`}
export function renderActivity(items=[]){app().innerHTML=`<h1>今天做什麼</h1><section class="card"><form id="activity-form"><div class="form-group"><label>目前狀態</label><select name="location"><option>各自在不同地方</option><option>在家</option><option>戶外</option><option>車上可以到</option><option>都可以</option></select></div><div class="grid two"><div class="form-group"><label>時間</label><select name="duration"><option value="10">10 分鐘</option><option value="20">20 分鐘</option><option value="30">30 分鐘</option><option value="60">1 小時</option><option value="120">2 小時</option></select></div><div class="form-group"><label>預算</label><select name="budget"><option value="0">不花錢</option><option value="300">300 元內</option><option value="600">600 元內</option><option value="1000">1,000 元內</option></select></div></div>${button("幫我們挑活動","recommend-activity")}</form></section>${items.length?`<section><h2>今天的活動提案</h2>${items.map(x=>`<article class="card recommendation"><span class="badge">${x.category}</span><h3>${x.title}</h3><p>${x.description}</p><small>${x.minDuration} 分鐘起｜${x.budget?"約 "+x.budget+" 元":"不用花錢"}｜${x.rewardSuggestion}</small></article>`).join("")}</section>`:""}`}
export function renderGames(){app().innerHTML=`<h1>雙人遊戲室</h1><section class="card"><h2>默契大考驗</h2><p>5 題，猜猜彼此的答案。</p>${button("開一場默契挑戰","new-room:compatibility")}</section><section class="card"><h2>誰比較可能</h2><p>10 題，公布後一起哈哈哈哈。</p>${button("開一場誰比較可能","new-room:likely")}</section><section class="card"><h2>猜對方答案</h2><p>一人先回答，另一人來猜。</p>${button("開一場猜答案","new-room:guess")}</section>`}
export function renderGameForm(room,questions){app().innerHTML=`<h1>${room.subtype==="compatibility"?"默契大考驗":room.subtype==="likely"?"誰比較可能":"猜對方答案"}</h1><section class="card"><p>邀請對方後，答案會先鎖住。</p>${button("分享遊戲邀請","share-room","button secondary")}</section><form id="game-form" class="card">${questions.map((q,i)=>`<div class="form-group"><label>${i+1}. ${q.text}</label>${q.type==="text"?`<input name="${q.id}" required placeholder="寫下你的答案">`:`<div class="grid">${q.options.map(o=>`<button type="button" class="choice" data-question="${q.id}" data-value="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join("")}</div><input type="hidden" name="${q.id}" required>`}</div>`).join("")}${button("鎖定我的答案","submit-game")}</form>`}
export function renderWaiting(room){app().innerHTML=`<h1>等待對方回答</h1><section class="card waiting"><h2>答案先鎖起來囉</h2><p>${pick(MESSAGES.waiting)}</p><div class="stat"><span>房間代碼</span><b class="room-code">${room.room_id}</b></div><div class="stat"><span>建立時間</span><span>${formatDate(room.created_at)}</span></div><div class="stat"><span>對方狀態</span><span>${room.answers?.[room.partner_user_id]?"已完成":"還沒回答"}</span></div>${button("分享邀請","share-room")}${button("重新整理","refresh-room","button secondary")}${button("取消房間","cancel-room","button ghost")}</section>`}
export function renderPending(rooms=[]){app().innerHTML=`<h1>等待中的邀請</h1>${rooms.length?rooms.map(r=>`<article class="card"><h2>${r.type==="dinner"?"晚餐秘密配對":r.subtype}</h2><p>${r.status==="completed"?"已完成。":"等待對方作答中。"}</p><small>為了保護房間答案，請從原本的邀請連結開啟此房間。</small></article>`).join(""):`<section class="card empty">目前沒有等待中的邀請。<br>去開一局給對方吧。</section>`}`}
export function renderHistory(){app().innerHTML=`<h1>歷史紀錄</h1><section class="card">${state.history.length?state.history.map(x=>`<div class="list-item"><b>${escapeHtml(x.title)}</b><br><small>${formatDate(x.created_at)}｜${x.points||0} 分</small></div>`).join(""):"<div class='empty'>還沒有共同紀錄，第一局很快就會出現。</div>"}</section>`}
export function renderSettings(){app().innerHTML=`<h1>設定與連線測試</h1><section class="card"><div class="stat"><span>API URL</span><span>${isConfigured()?"已設定":"尚未設定（Mock 模式）"}</span></div>${button("測試 API 連線","health")}${button("建立測試房間","new-room:dinner","button secondary")}${button("切換身分","change-identity","button secondary")}${button("清除本機身分","clear-identity","button ghost")}</section><p class="version">版本 1.0.0</p>`}
export function renderError(message){app().innerHTML=`<section class="card"><h1>哎呀，這裡卡住了</h1><p>${escapeHtml(message)}</p>${button("回首頁","route:home")}</section>`}
