/*
 * 大爺與阡阡生活遊樂場 API。請貼到「綁定私人試算表」的 Apps Script 專案。
 * 先執行 setupSpreadsheet，再部署為 Web App（以我身分執行）。
 */
var SHEETS={Users:["user_id","display_name","pin_hash","role","created_at","updated_at"],Rooms:["room_id","room_token_hash","type","subtype","creator_user_id","partner_user_id","status","created_at","expires_at","completed_at","result_id"],Answers:["answer_id","room_id","user_id","payload_json","submitted_at"],Results:["result_id","room_id","result_json","score","created_at"],History:["history_id","room_id","type","title","summary","participants","created_at"],ActivityData:["item_id","category","payload_json","enabled","updated_at"],Logs:["log_id","action","room_id","user_id","status","message","created_at"]};
function doGet(e){return response(dispatch(Object.assign({action:"healthCheck"},e.parameter||{})));}
function doPost(e){try{return response(dispatch(JSON.parse(e.postData&&e.postData.contents||"{}")));}catch(err){return response(fail("INVALID_REQUEST","請求格式不正確。"));}}
function response(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
function ok(data,message){return{success:true,data:data||{},message:message||""};}function fail(code,message){return{success:false,errorCode:code,message:message};}
function dispatch(p){try{var action=p.action;if(action==="healthCheck")return ok({status:"ok",time:iso()});if(action==="setupSpreadsheet")return setupSpreadsheet();if(action==="verifyPin")return verifyPin(p);if(action==="createRoom")return createRoom(p);if(action==="getRoom")return getRoom(p);if(action==="submitAnswer")return submitAnswer(p);if(action==="calculateResult")return calculateResult(p);if(action==="getPendingRooms")return pendingRooms(p);if(action==="getHistory")return getHistory(p);if(action==="cancelRoom")return cancelRoom(p);if(action==="voteResult")return voteResult(p);if(action==="deleteExpiredRooms")return deleteExpiredRooms();return fail("UNKNOWN_ACTION","找不到指定操作。");}catch(err){log("error","","","error",String(err));return fail("SERVER_ERROR","資料處理暫時失敗，請再試一次。");}}
function setupSpreadsheet(){var ss=SpreadsheetApp.getActiveSpreadsheet();if(!ss)throw new Error("請從目標 Google 試算表開啟 Apps Script 後執行。");PropertiesService.getScriptProperties().setProperty("SPREADSHEET_ID",ss.getId());Object.keys(SHEETS).forEach(function(name){var sh=ss.getSheetByName(name)||ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(SHEETS[name]);sh.setFrozenRows(1);});return ok({spreadsheetId:ss.getId()},"工作表已準備完成。");}
function ss(){var id=PropertiesService.getScriptProperties().getProperty("SPREADSHEET_ID");if(!id)throw new Error("Apps Script 尚未設定試算表，請先執行 setupSpreadsheet。");return SpreadsheetApp.openById(id);}
function sheet(name){return ss().getSheetByName(name);}
function iso(){return new Date().toISOString();}function hash(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8).map(function(b){return("0"+(b&255).toString(16)).slice(-2);}).join("");}
function rowToObj(name,row){var o={};SHEETS[name].forEach(function(h,i){o[h]=row[i]===undefined?"":row[i];});return o;}
function rows(name){var sh=sheet(name),v=sh.getDataRange().getValues();return v.slice(1).map(function(r){return rowToObj(name,r);});}
function find(name,key,value){return rows(name).filter(function(r){return String(r[key])===String(value);})[0];}
function add(name,o){sheet(name).appendRow(SHEETS[name].map(function(h){return o[h]===undefined?"":o[h];}));}
function update(name,key,value,patch){var sh=sheet(name),v=sh.getDataRange().getValues(),col=SHEETS[name].indexOf(key);for(var i=1;i<v.length;i++)if(String(v[i][col])===String(value)){SHEETS[name].forEach(function(h,j){if(patch[h]!==undefined)sh.getRange(i+1,j+1).setValue(patch[h]);});return;}throw new Error("找不到資料。");}
function log(action,room,user,status,message){try{add("Logs",{log_id:Utilities.getUuid(),action:action,room_id:room,user_id:user,status:status,message:message,created_at:iso()});}catch(e){}}
function requireFields(p,names){for(var i=0;i<names.length;i++)if(p[names[i]]===undefined||p[names[i]]==="")throw new Error("缺少必要資料："+names[i]);}
function verifyPin(p){requireFields(p,["user_id","pin"]);var user=find("Users","user_id",p.user_id);if(!user)return fail("USER_NOT_FOUND","尚未設定此使用者 PIN。");return user.pin_hash===hash(p.pin)?ok({verified:true}):fail("PIN_INVALID","PIN 不正確。");}
function createRoom(p){requireFields(p,["room"]);var r=p.room;requireFields(r,["room_id","room_token","type","creator_user_id","partner_user_id","expires_at"]);if(String(r.room_token).length<24)return fail("TOKEN_INVALID","邀請驗證碼長度不足。");if(find("Rooms","room_id",r.room_id))return fail("ROOM_EXISTS","房間代碼重複，請重新建立。");add("Rooms",{room_id:r.room_id,room_token_hash:hash(r.room_token),type:r.type,subtype:r.subtype||"",creator_user_id:r.creator_user_id,partner_user_id:r.partner_user_id,status:"waiting",created_at:r.created_at||iso(),expires_at:r.expires_at,completed_at:"",result_id:""});log("createRoom",r.room_id,r.creator_user_id,"ok","");var created=safeRoom(find("Rooms","room_id",r.room_id),r.creator_user_id);created.room_token=r.room_token;return ok(created);}
function checkRoom(p){requireFields(p,["room_id","room_token","user_id"]);var r=find("Rooms","room_id",p.room_id);if(!r)throw new Error("這個房間不存在，可能連結不完整。");if(r.room_token_hash!==hash(p.room_token))throw new Error("邀請連結驗證失敗。");if([r.creator_user_id,r.partner_user_id].indexOf(p.user_id)<0)throw new Error("此身分不屬於這個房間。");if(new Date(r.expires_at)<new Date()&&r.status==="waiting"){update("Rooms","room_id",r.room_id,{status:"expired"});r.status="expired";}if(r.status==="expired")throw new Error("這個邀請已經過期。");return r;}
function getRoom(p){var r=checkRoom(p);return ok(safeRoom(r,p.user_id));}
function safeRoom(r,user){var out={room_id:r.room_id,type:r.type,subtype:r.subtype,creator_user_id:r.creator_user_id,partner_user_id:r.partner_user_id,status:r.status,created_at:r.created_at,expires_at:r.expires_at,completed_at:r.completed_at,result_id:r.result_id,answers:{}};var ans=rows("Answers").filter(function(a){return a.room_id===r.room_id;});ans.forEach(function(a){if(r.status==="completed"||a.user_id===user)out.answers[a.user_id]=JSON.parse(a.payload_json);});if(r.status==="completed"&&r.result_id){var result=find("Results","result_id",r.result_id);out.result=result?JSON.parse(result.result_json):null;}return out;}
function submitAnswer(p){var lock=LockService.getScriptLock();lock.waitLock(20000);try{requireFields(p,["room_id","room_token","user_id","payload"]);var r=checkRoom(p);if(r.status!=="waiting")return fail("ROOM_LOCKED","這個房間目前不能再回答。");if(find("Answers","room_id",p.room_id)&&rows("Answers").some(function(a){return a.room_id===p.room_id&&a.user_id===p.user_id;}))return fail("DUPLICATE_ANSWER","你已經回答過囉。");add("Answers",{answer_id:Utilities.getUuid(),room_id:r.room_id,user_id:p.user_id,payload_json:JSON.stringify(p.payload),submitted_at:iso()});var all=rows("Answers").filter(function(a){return a.room_id===r.room_id;});if(all.length>=2)finishRoom(r);return ok(safeRoom(find("Rooms","room_id",r.room_id),p.user_id));}finally{lock.releaseLock();}}
function finishRoom(r){var a=rows("Answers").filter(function(x){return x.room_id===r.room_id;});var payloads=a.map(function(x){return JSON.parse(x.payload_json);});var score=0,title="雙人遊戲完成",summary="兩人一起完成了一場小挑戰。";if(r.type==="dinner"){score=80;title="今晚晚餐秘密配對";summary="答案都解鎖了，快一起選今晚吃什麼。";}else{var left=payloads[0]||[],right=payloads[1]||[];if(Array.isArray(left)&&Array.isArray(right)){var hit=left.filter(function(v,i){return v===right[i];}).length;score=Math.round(hit/Math.max(left.length,1)*100);summary="默契分數 "+score+" 分。";}}var result={score:score,items:[],summary:summary};var id=Utilities.getUuid();add("Results",{result_id:id,room_id:r.room_id,result_json:JSON.stringify(result),score:score,created_at:iso()});update("Rooms","room_id",r.room_id,{status:"completed",completed_at:iso(),result_id:id});add("History",{history_id:Utilities.getUuid(),room_id:r.room_id,type:r.type,title:title,summary:summary,participants:r.creator_user_id+","+r.partner_user_id,created_at:iso()});}
function calculateResult(p){var r=checkRoom(p);if(r.status!=="completed")return fail("ANSWERS_HIDDEN","現在還不能偷看對方答案。");return ok(safeRoom(r,p.user_id).result);}
function pendingRooms(p){requireFields(p,["user_id"]);var list=rows("Rooms").filter(function(r){return(r.creator_user_id===p.user_id||r.partner_user_id===p.user_id)&&["waiting","completed"].indexOf(r.status)>=0;}).slice(-30).reverse().map(function(r){return safeRoom(r,p.user_id);});return ok(list);}
function getHistory(p){requireFields(p,["user_id"]);var h=rows("History").filter(function(x){return x.participants.split(",").indexOf(p.user_id)>=0;}).slice(-50).reverse();return ok(h);}
function cancelRoom(p){var r=checkRoom(p);if(r.creator_user_id!==p.user_id)return fail("NOT_CREATOR","只有建立者可以取消房間。");if(r.status!=="waiting")return fail("ROOM_LOCKED","已完成的房間不能取消。");update("Rooms","room_id",r.room_id,{status:"cancelled"});return ok({});}
function voteResult(p){var r=checkRoom(p);if(r.status!=="completed")return fail("ROOM_NOT_COMPLETED","完成後才能投票。");log("voteResult",r.room_id,p.user_id,"ok",JSON.stringify(p.vote||{}));return ok({});}
function deleteExpiredRooms(){var count=0;rows("Rooms").forEach(function(r){if(r.status==="waiting"&&new Date(r.expires_at)<new Date()){update("Rooms","room_id",r.room_id,{status:"expired"});count++;}});return ok({expired:count});}
