/*
 * 大爺與阡阡生活遊樂場 API。請貼到「綁定私人試算表」的 Apps Script 專案。
 * 先執行 setupSpreadsheet，再部署為 Web App（以我身分執行）。
 */
var SHEETS={Users:["user_id","display_name","pin_hash","role","created_at","updated_at"],Rooms:["room_id","room_token_hash","type","subtype","creator_user_id","partner_user_id","status","created_at","expires_at","completed_at","result_id"],Answers:["answer_id","room_id","user_id","payload_json","submitted_at"],Results:["result_id","room_id","result_json","score","created_at"],History:["history_id","room_id","type","title","summary","participants","created_at"],ActivityData:["item_id","category","payload_json","enabled","updated_at"],Logs:["log_id","action","room_id","user_id","status","message","created_at"],LanyuMissions:["date","mission_id","mission_text","assigned_by","assigned_to","status","created_at","completed_at"],LanyuBottles:["date","sender_user_id","receiver_user_id","message","created_at","opened_at"]};
var LANYU_START="2026-09-03",LANYU_END="2026-09-11",LANYU_TZ="Asia/Taipei";
var LANYU_MISSIONS={"2026-09-03":{"d0903-a":"💌 上車後跟我說一聲","d0903-b":"📸 拍一張「旅程開始了」的照片","d0903-c":"🎵 傳一首今晚坐車想聽的歌給我"},"2026-09-04":{"d0904-a":"🐠 找一隻魚代表我","d0904-b":"📸 拍今天看到最漂亮的東西","d0904-c":"💌 上岸第一件事傳訊息給我"},"2026-09-05":{"d0905-a":"🌅 拍一張日出給我","d0905-b":"🌊 錄 10 秒海浪聲給我","d0905-c":"📸 拍一張「如果阡阡也在這裡」的照片"},"2026-09-06":{"d0906-a":"🐠 找一個海底東西讓你想到我","d0906-b":"📸 拍今天最好看的海底照片","d0906-c":"😂 拍一張今天最白痴的照片"},"2026-09-07":{"d0907-a":"🎂 生日第一個願望偷偷留一個給我","d0907-b":"🥂 今天第一杯敬我","d0907-c":"📸 拍一張最荒謬的生日照片"},"2026-09-08":{"d0908-a":"🤿 出水後第一件事跟我報平安","d0908-b":"🐠 找一隻今天最可愛的魚","d0908-c":"📸 今天最喜歡的潛水照片留給我"},"2026-09-09":{"d0909-a":"🌄 幫我拍一張「如果我也在這裡」的夕陽","d0909-b":"🎵 選一首歌配今天的夕陽","d0909-c":"💌 晚上告訴我今天最喜歡的一件事"},"2026-09-10":{"d0910-a":"🐠 跟蘭嶼的海幫我說掰掰","d0910-b":"📸 拍一張最後一潛紀念照","d0910-c":"💌 告訴我這趟最想帶我來哪裡"},"2026-09-11":{"d0911-a":"🎁 幫我挑一個伴手禮","d0911-b":"📸 拍最後一張蘭嶼照片給我","d0911-c":"❤️ 告訴我回台北第一件想跟我做的事"}};
function doGet(e){return response(dispatch(Object.assign({action:"healthCheck"},(e&&e.parameter)||{})));}
function doPost(e){try{return response(dispatch(JSON.parse(e.postData&&e.postData.contents||"{}")));}catch(err){return response(fail("INVALID_REQUEST","請求格式不正確。"));}}
function response(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);}
function ok(data,message){return{success:true,data:data||{},message:message||""};}function fail(code,message){return{success:false,errorCode:code,message:message};}
function dispatch(p){try{var action=p.action;if(action==="healthCheck")return ok({status:"ok",time:iso()});if(action==="setupSpreadsheet")return setupSpreadsheet();if(action==="verifyPin")return verifyPin(p);if(action==="createRoom")return createRoom(p);if(action==="getRoom")return getRoom(p);if(action==="submitAnswer")return submitAnswer(p);if(action==="calculateResult")return calculateResult(p);if(action==="getPendingRooms")return pendingRooms(p);if(action==="getHistory")return getHistory(p);if(action==="cancelRoom")return cancelRoom(p);if(action==="voteResult")return voteResult(p);if(action==="deleteExpiredRooms")return deleteExpiredRooms();if(action==="getLanyuState")return getLanyuState(p);if(action==="assignLanyuMission")return assignLanyuMission(p);if(action==="completeLanyuMission")return completeLanyuMission(p);if(action==="sendLanyuBottle")return sendLanyuBottle(p);if(action==="openLanyuBottle")return openLanyuBottle(p);return fail("UNKNOWN_ACTION","找不到指定操作。");}catch(err){log("error","","","error",String(err));return fail("SERVER_ERROR","資料處理暫時失敗，請再試一次。");}}
function assertSheetHeader(name,sh){var expected=SHEETS[name];if(sh.getLastRow()===0){sh.appendRow(expected);return;}var actual=sh.getRange(1,1,1,Math.max(sh.getLastColumn(),expected.length)).getValues()[0].map(String);if(actual.length!==expected.length||expected.some(function(header,index){return actual[index]!==header;}))throw new Error("工作表「"+name+"」Header 不一致；為保護既有資料，程式沒有修改任何欄位。");}
function setupSpreadsheet(){var ss=SpreadsheetApp.getActiveSpreadsheet();if(!ss)throw new Error("請從目標 Google 試算表開啟 Apps Script 後執行。");PropertiesService.getScriptProperties().setProperty("SPREADSHEET_ID",ss.getId());Object.keys(SHEETS).forEach(function(name){var sh=ss.getSheetByName(name)||ss.insertSheet(name);assertSheetHeader(name,sh);sh.setFrozenRows(1);});return ok({spreadsheetId:ss.getId()},"工作表已準備完成。");}
function ss(){var id=PropertiesService.getScriptProperties().getProperty("SPREADSHEET_ID");if(!id)throw new Error("Apps Script 尚未設定試算表，請先執行 setupSpreadsheet。");return SpreadsheetApp.openById(id);}
function sheet(name){return ss().getSheetByName(name);}
function iso(){return new Date().toISOString();}function hash(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8).map(function(b){return("0"+(b&255).toString(16)).slice(-2);}).join("");}
function rowToObj(name,row){var o={};SHEETS[name].forEach(function(h,i){o[h]=row[i]===undefined?"":row[i];});return o;}
function rows(name){var sh=sheet(name),v=sh.getDataRange().getValues();return v.slice(1).map(function(r){return rowToObj(name,r);});}
function find(name,key,value){return rows(name).filter(function(r){return String(r[key])===String(value);})[0];}
function add(name,o){sheet(name).appendRow(SHEETS[name].map(function(h){return o[h]===undefined?"":o[h];}));}
function update(name,key,value,patch){var sh=sheet(name),v=sh.getDataRange().getValues(),col=SHEETS[name].indexOf(key);for(var i=1;i<v.length;i++)if(String(v[i][col])===String(value)){SHEETS[name].forEach(function(h,j){if(patch[h]!==undefined)sh.getRange(i+1,j+1).setValue(patch[h]);});return;}throw new Error("找不到資料。");}
function log(action,room,user,status,message){try{add("Logs",{log_id:Utilities.getUuid(),action:action,room_id:room,user_id:user,status:status,message:message,created_at:iso()});}catch(e){}}
function requireFields(p,names){for(var i=0;i<names.length;i++)if(p[names[i]]===undefined||p[names[i]]==="")throw new Error("缺少必要資料："+names[i]);}
function verifyPin(p){requireFields(p,["user_id","pin"]);var user=find("Users","user_id",p.user_id);if(!user)return fail("USER_NOT_FOUND","尚未設定此使用者 PIN。");return user.pin_hash===hash(p.pin)?ok({verified:true}):fail("PIN_INVALID","PIN 不正確。");}
function createRoom(p){requireFields(p,["room"]);var r=p.room;requireFields(r,["room_id","room_token","type","creator_user_id","partner_user_id","expires_at"]);if(String(r.room_token).length<24)return fail("TOKEN_INVALID","邀請驗證碼長度不足。");if(find("Rooms","room_id",r.room_id))return fail("ROOM_EXISTS","房間代碼重複，請重新建立。");add("Rooms",{room_id:r.room_id,room_token_hash:hash(r.room_token),type:r.type,subtype:r.subtype||"",creator_user_id:r.creator_user_id,partner_user_id:r.partner_user_id,status:"waiting",created_at:r.created_at||iso(),expires_at:r.expires_at,completed_at:"",result_id:""});log("createRoom",r.room_id,r.creator_user_id,"ok","");var created=safeRoom(find("Rooms","room_id",r.room_id),r.creator_user_id);created.room_token=r.room_token;return ok(created);}
function checkRoom(p){requireFields(p,["room_id","room_token","user_id"]);var r=find("Rooms","room_id",p.room_id);if(!r)throw new Error("這個房間不存在，可能連結不完整。");if(r.room_token_hash!==hash(p.room_token))throw new Error("邀請連結驗證失敗。");if([r.creator_user_id,r.partner_user_id].indexOf(p.user_id)<0)throw new Error("此身分不屬於這個房間。");if(new Date(r.expires_at)<new Date()&&r.status==="waiting"){update("Rooms","room_id",r.room_id,{status:"expired"});r.status="expired";}if(r.status==="expired")throw new Error("這個邀請已經過期。");return r;}
function getRoom(p){var r=checkRoom(p);return ok(safeRoom(r,p.user_id));}
function safeRoom(r,user){var out={room_id:r.room_id,type:r.type,subtype:r.subtype,creator_user_id:r.creator_user_id,partner_user_id:r.partner_user_id,status:r.status,created_at:r.created_at,expires_at:r.expires_at,completed_at:r.completed_at,result_id:r.result_id,answers:{}};var ans=rows("Answers").filter(function(a){return a.room_id===r.room_id;});ans.forEach(function(a){if(r.status==="completed"||a.user_id===user)out.answers[a.user_id]=JSON.parse(a.payload_json);});if(r.status==="completed"&&r.result_id){var result=find("Results","result_id",r.result_id);out.result=result?JSON.parse(result.result_json):null;}return out;}
function submitAnswer(p){var lock=LockService.getScriptLock();lock.waitLock(20000);try{requireFields(p,["room_id","room_token","user_id","payload"]);var r=checkRoom(p);if(r.status!=="waiting")return fail("ROOM_LOCKED","這個房間目前不能再回答。");if(find("Answers","room_id",p.room_id)&&rows("Answers").some(function(a){return a.room_id===p.room_id&&a.user_id===p.user_id;}))return fail("DUPLICATE_ANSWER","你已經回答過囉。");add("Answers",{answer_id:Utilities.getUuid(),room_id:r.room_id,user_id:p.user_id,payload_json:JSON.stringify(p.payload),submitted_at:iso()});var all=rows("Answers").filter(function(a){return a.room_id===r.room_id;});if(all.length>=2)finishRoom(r);return ok(safeRoom(find("Rooms","room_id",r.room_id),p.user_id));}finally{lock.releaseLock();}}
function finishRoom(r){var a=rows("Answers").filter(function(x){return x.room_id===r.room_id;});var payloads=a.map(function(x){return JSON.parse(x.payload_json);});var score=0,title="雙人遊戲完成",summary="兩人一起完成了一場小挑戰。";if(r.type==="dinner"){score=80;title="今晚晚餐秘密配對";summary="答案都解鎖了，快一起選今晚吃什麼。";}else{var left=payloads[0]||[],right=payloads[1]||[];if(Array.isArray(left)&&Array.isArray(right)){var hit=left.filter(function(v,i){return v===right[i];}).length;score=Math.round(hit/Math.max(left.length,1)*100);summary="默契分數 "+score+" 分。";}}var result={score:score,items:[],summary:summary};var id=Utilities.getUuid();add("Results",{result_id:id,room_id:r.room_id,result_json:JSON.stringify(result),score:score,created_at:iso()});update("Rooms","room_id",r.room_id,{status:"completed",completed_at:iso(),result_id:id});add("History",{history_id:Utilities.getUuid(),room_id:r.room_id,type:r.type,title:title,summary:summary,participants:r.creator_user_id+","+r.partner_user_id,created_at:iso()});}
function calculateResult(p){var r=checkRoom(p);if(r.status!=="completed")return fail("ANSWERS_HIDDEN","現在還不能偷看對方答案。");return ok(safeRoom(r,p.user_id).result);}
function pendingRooms(p){requireFields(p,["user_id"]);var list=rows("Rooms").filter(function(r){return(r.creator_user_id===p.user_id||r.partner_user_id===p.user_id)&&["waiting","completed"].indexOf(r.status)>=0;}).slice(-30).reverse().map(function(r){return safeRoom(r,p.user_id);});return ok(list);}
function getHistory(p){requireFields(p,["user_id"]);var h=rows("History").filter(function(x){return x.participants.split(",").indexOf(p.user_id)>=0;}).slice(-50).reverse();return ok(h);}
function cancelRoom(p){var r=checkRoom(p);if(r.creator_user_id!==p.user_id)return fail("NOT_CREATOR","只有建立者可以取消房間。");if(r.status!=="waiting")return fail("ROOM_LOCKED","已完成的房間不能取消。");update("Rooms","room_id",r.room_id,{status:"cancelled"});return ok({});}
function voteResult(p){var r=checkRoom(p);if(r.status!=="completed")return fail("ROOM_NOT_COMPLETED","完成後才能投票。");log("voteResult",r.room_id,p.user_id,"ok",JSON.stringify(p.vote||{}));return ok({});}
function deleteExpiredRooms(){var count=0;rows("Rooms").forEach(function(r){if(r.status==="waiting"&&new Date(r.expires_at)<new Date()){update("Rooms","room_id",r.room_id,{status:"expired"});count++;}});return ok({expired:count});}
function lanyuToday(){return Utilities.formatDate(new Date(),LANYU_TZ,"yyyy-MM-dd");}
function lanyuUser(user){if(["ken","chien"].indexOf(user)<0)throw new Error("INVALID_USER");}
function lanyuReadDate(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error("INVALID_DATE");}
function lanyuDate(date,write){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date<LANYU_START||date>LANYU_END)throw new Error("DATE_OUT_OF_RANGE");if(write&&date!==lanyuToday())throw new Error("DATE_NOT_TODAY");}
function lanyuLock(fn){var lock=LockService.getScriptLock();lock.waitLock(20000);try{return fn();}finally{lock.releaseLock();}}
function lanyuMission(date){return find("LanyuMissions","date",date);}
function lanyuBottle(date,sender){return rows("LanyuBottles").filter(function(b){return b.date===date&&b.sender_user_id===sender;})[0];}
function lanyuStatsFrom(missions,bottles,user){var start=new Date(LANYU_START+"T00:00:00Z"),now=new Date(lanyuToday()+"T00:00:00Z"),progress=Math.max(0,Math.min(100,Math.round((now-start)/86400000/8*100)));return{assigned:missions.length,completed:missions.filter(function(m){return m.status==="completed";}).length,received:bottles.filter(function(b){return b.receiver_user_id===user;}).length,progress:progress};}
function lanyuViewBottle(b,user){if(!b)return null;var out={exists:true,opened:!!b.opened_at,sender_name:b.sender_user_id==="ken"?"大爺":"阡阡"};if(b.sender_user_id===user||b.opened_at)out.message=b.message;return out;}
function getLanyuState(p){lanyuUser(p.user_id);var date=p.date||lanyuToday();lanyuReadDate(date);var allMissions=rows("LanyuMissions"),allBottles=rows("LanyuBottles"),missionByDate={};allMissions.forEach(function(m){missionByDate[m.date]=m;});var bottleByKey={};allBottles.forEach(function(b){bottleByKey[b.date+":"+b.sender_user_id]=b;});var mission=missionByDate[date]||null,mine=bottleByKey[date+":"+p.user_id]||null,other=bottleByKey[date+":"+(p.user_id==="ken"?"chien":"ken")]||null;var timeline=Object.keys(LANYU_MISSIONS).map(function(d){return{date:d,label:d.slice(5).replace("-","/"),mission:missionByDate[d]||null,bottles:allBottles.filter(function(b){return b.date===d;}).map(function(b){return{sender_user_id:b.sender_user_id};})};});var dayMissions=Object.keys(LANYU_MISSIONS[date]||{}).map(function(id){var text=LANYU_MISSIONS[date][id],parts=text.split(" ");return{id:id,emoji:parts.shift(),text:parts.join(" ")};});return ok({date:date,day:{date:date,missions:dayMissions},mission:mission,bottle:{mine:mine,theirs:lanyuViewBottle(other,p.user_id)},stats:lanyuStatsFrom(allMissions,allBottles,p.user_id),timeline:timeline});}
function assignLanyuMission(p){return lanyuLock(function(){lanyuUser(p.user_id);lanyuDate(p.date,true);if(p.user_id!=="chien")return fail("NOT_CHIEN","這個遙控器是阡阡專用。");if(lanyuMission(p.date))return fail("MISSION_ALREADY_ASSIGNED","今天已經選過任務了。");var text=LANYU_MISSIONS[p.date]&&LANYU_MISSIONS[p.date][p.mission_id];if(!text)return fail("INVALID_MISSION","這個任務不在今天的清單裡。");add("LanyuMissions",{date:p.date,mission_id:p.mission_id,mission_text:text,assigned_by:"chien",assigned_to:"ken",status:"pending",created_at:iso(),completed_at:""});return getLanyuState(p);});}
function completeLanyuMission(p){return lanyuLock(function(){lanyuUser(p.user_id);lanyuDate(p.date,true);if(p.user_id!=="ken")return fail("NOT_KEN","這個按鈕是大爺專用。");var m=lanyuMission(p.date);if(!m)return fail("MISSION_NOT_FOUND","今天沒有可完成的任務。");if(m.status==="completed")return fail("MISSION_ALREADY_COMPLETED","今天的任務已完成。");update("LanyuMissions","date",p.date,{status:"completed",completed_at:iso()});return getLanyuState(p);});}
function sendLanyuBottle(p){return lanyuLock(function(){lanyuUser(p.user_id);lanyuDate(p.date,true);var message=String(p.message||"").trim();if(!message||[...message].length>100)return fail("MESSAGE_INVALID","漂流瓶內容需介於 1 到 100 字。");if(lanyuBottle(p.date,p.user_id))return fail("BOTTLE_ALREADY_SENT","今天已經丟過漂流瓶了。");add("LanyuBottles",{date:p.date,sender_user_id:p.user_id,receiver_user_id:p.user_id==="ken"?"chien":"ken",message:message,created_at:iso(),opened_at:""});return getLanyuState(p);});}
function openLanyuBottle(p){return lanyuLock(function(){lanyuUser(p.user_id);lanyuDate(p.date,false);var sender=p.user_id==="ken"?"chien":"ken",b=lanyuBottle(p.date,sender);if(!b)return fail("BOTTLE_NOT_FOUND","今天沒有漂流瓶。");if(b.receiver_user_id!==p.user_id)return fail("NOT_RECEIVER","只有收件人能打開漂流瓶。");if(!b.opened_at){var sh=sheet("LanyuBottles"),v=sh.getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][0])===p.date&&String(v[i][1])===sender){sh.getRange(i+1,6).setValue(iso());break;}}return getLanyuState(p);});}
